### ISSUE TITLE
To the top button

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/awaas-vishwa-fe#13]
When user scroll down, we need to show a button on bottom right to the top. Button is invisible at the top and only visible after scroll 300px.

**Comment by Halim-Shams** [comment]
I can figure it out :)

**Comment by ahmohil** [comment]
Assign this to me

**Comment by omrajsharma** [comment]
@ahmohil I've assigned this issue to you. If you need any help then do let me know.

**Comment by ahmohil** [comment]
Yeah! sure

**Comment by ahmohil** [comment]
@omrajsharma  Yeah! Sure

**Comment by ahmohil** [comment]
The site is not loading any page that might, reason might be the missing BASE_URL that is in the .env


![notloadProducts](https://github.com/omrajsharma/awaas-vishwa-fe/assets/53046043/cdc6f9fd-1d6e-4f57-92f7-d703ed53da8d)

**Comment by omrajsharma** [comment]
You can try this without the data by, just put some lorem text

**Comment by omrajsharma** [comment]
You can also use https://awaas-vishwa-be.onrender.com as your base url

**Comment by omrajsharma** [comment]
#19

**Comment by omrajsharma** [comment]
Merged PR #19
