### ISSUE TITLE
Dark mode feature Enable.

### ISSUE THREAD

**Issue by Urvashi021** [omrajsharma/awaas-vishwa-fe#14]

**Comment by Faisalhs51** [comment]
@omrajsharma  assign this to me

**Comment by omrajsharma** [comment]
@Faisalhs51 I've assigned this issue to you. Let me know if you need any help.

**Comment by Faisalhs51** [comment]
@omrajsharma Where to place the dark mode toggle button in mobile view?

**Comment by omrajsharma** [comment]
PR #25 merged
