### ISSUE TITLE
Default Readme.md

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/awaas-vishwa-fe#2]
Need to update readme.md
- about project
- project setup
- how to contribute (optional)
- top contributors

**Comment by thezeeshann** [comment]
@omrajsharma assign me this issue. I can create an updated readme file.

**Comment by omrajsharma** [comment]
@thezeeshann assigned the issue. let me know if you need any help.

**Comment by shruti-202** [comment]
@omrajsharma Please assign me this issue.

**Comment by omrajsharma** [comment]
Sure Shruti, I'm assigning this issue to you. Please let me know if you need any help

**Comment by omrajsharma** [comment]
PR #10 is merged
Thanks @shruti-202 for your contribution
