### ISSUE TITLE
navbar overlapping the content

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/awaas-vishwa-fe#21]
<img width="405" alt="Screenshot 2023-09-08 at 7 56 43 AM" src="https://github.com/omrajsharma/awaas-vishwa-fe/assets/60071210/dfd316e0-1622-42be-b558-f7efe222d71b">
on scroll the navbar is over lapping the content

**Comment by mustachemo** [comment]
Hello, I believe i can solve this. Can I be assigned to it please?

**Comment by corners2wall** [comment]
Needs just add `position: static` to the button component

**Comment by omrajsharma** [comment]
@corners2wall would you like to work on this issue?

**Comment by corners2wall** [comment]
@omrajsharma  no 🙄

**Comment by rishikush31** [comment]
i would work on it

**Comment by corners2wall** [comment]
@rishikush31  good luck

**Comment by rishikush31** [comment]
> @rishikush31 good luck

i am just getting into opensource so yeah

**Comment by corners2wall** [comment]
@rishikush31  I too

**Comment by rishikush31** [comment]
> @rishikush31 I too

can you guide me a little, i am not able to find a repo to start contributing to which is active.

**Comment by corners2wall** [comment]
@rishikush31  I contribute in any repo. I find issue and if I understand clearly description I try resolve issue

**Comment by rishikush31** [comment]
Thats good.

**Comment by omrajsharma** [comment]
Sure @rishikush31 I'm this assigning issue

**Comment by Riteshgtm12** [comment]
You Can Assign me this issue i'll fix it

**Comment by omrajsharma** [comment]
issue is resolved in PR #25
