### ISSUE TITLE
no tooltip provided for user registration

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/awaas-vishwa-fe#3]

**Comment by Urvashi021** [comment]
assign me this issue.

**Comment by omrajsharma** [comment]
@Urvashi021 I've assigned this issue. please ask for any help required.

**Comment by Riteshgtm12** [comment]
Can you please explain to me what you want in the tooltip?
I think you want a tool like the password hide and show tool in the registration form. if Yes?
Then you can assign me the task, If @Urvashi021 is not working on this issue currently.

**Comment by omrajsharma** [comment]
PR #9 merged
Thanks @Urvashi021 for your contribution
