### ISSUE TITLE
no login button in the register form 

### ISSUE THREAD

**Issue by omrajsharma** [omrajsharma/awaas-vishwa-fe#5]

**Comment by anubhav1206** [comment]
Can you elaborate on the issue? Why would there be a login button in the registration form? A signup button would make more sense.

**Comment by Riteshgtm12** [comment]
I think the button doesn't look good, but add this line: "'Already have an account? Login"'  at the bottom of the sign-up button. and Login text is linked to the login page.
Please assign me, and I will fix this issue.

**Comment by omrajsharma** [comment]
@Riteshgtm12 I've assigned this issue, feel free to reachout for any issue.
